<?php

/**
 * Webhook subscriptions screen.
 *
 * @package    ArtisanPack_UI
 * @subpackage EcommerceAdminLivewire
 *
 * @since      1.0.0
 */

declare( strict_types=1 );

namespace ArtisanPackUI\EcommerceAdminLivewire\Livewire\Webhooks;

use ArtisanPackUI\Ecommerce\Http\Requests\Api\V1\WebhookSubscriptionRequest;
use ArtisanPackUI\Ecommerce\Models\WebhookSubscription;
use ArtisanPackUI\Ecommerce\Services\WebhookSubscriptionService;
use ArtisanPackUI\EcommerceAdminLivewire\Livewire\Concerns\AuthorizesEcommerce;
use ArtisanPackUI\EcommerceAdminLivewire\Livewire\Concerns\SendsToasts;
use ArtisanPackUI\EcommerceAdminLivewire\Livewire\Concerns\WithActionToken;
use ArtisanPackUI\EcommerceAdminLivewire\Livewire\Concerns\WithResourceTable;
use ArtisanPackUI\EcommerceAdminLivewire\Livewire\Webhooks\Concerns\ManagesWebhookSubscriptions;
use ArtisanPackUI\EcommerceAdminLivewire\Queries\ResourceQuery;
use ArtisanPackUI\EcommerceAdminLivewire\Queries\WebhookSubscriptionsQuery;
use ArtisanPackUI\EcommerceAdminLivewire\Support\Authorization;
use ArtisanPackUI\EcommerceAdminLivewire\Support\Webhooks;
use Illuminate\Contracts\View\View;
use Livewire\Attributes\Locked;
use Livewire\Component;

/**
 * The webhook subscriptions table (spec §7.8): name, URL, events, state,
 * last success, last failure, and consecutive failures.
 *
 * - Create and edit happen in a drawer. The engine's URL rules (HTTPS
 *   unless insecure URLs are allowed; no private or loopback hosts) come
 *   from `WebhookSubscriptionRequest::baseRules()`, so they surface as
 *   field errors here.
 * - The signing secret is generated by the engine on create and shown
 *   once; "rotate secret" replaces it after confirmation and shows the new
 *   one once.
 * - A subscription the engine disabled after repeated failures can be
 *   re-enabled, which resets its failure count.
 * - Deleting asks for confirmation and carries a one-time action token;
 *   the subscription's deliveries go with it.
 *
 * @package    ArtisanPack_UI
 * @subpackage EcommerceAdminLivewire
 *
 * @since      1.0.0
 */
class Index extends Component
{
    use AuthorizesEcommerce;
    use ManagesWebhookSubscriptions;
    use SendsToasts;
    use WithActionToken;
    use WithResourceTable;

    /**
     * Whether the create/edit drawer is open.
     *
     * @since 1.0.0
     *
     * @var bool
     */
    public bool $editing = false;

    /**
     * The subscription being edited, or null when creating.
     *
     * @since 1.0.0
     *
     * @var int|null
     */
    #[Locked]
    public ?int $subscriptionId = null;

    /**
     * The form fields.
     *
     * @since 1.0.0
     *
     * @var array{name: string, url: string, events: array<int, string>, is_active: bool}
     */
    public array $form = [
        'name'      => '',
        'url'       => '',
        'events'    => [],
        'is_active' => true,
    ];

    /**
     * The subscription waiting for delete confirmation.
     *
     * @since 1.0.0
     *
     * @var int|null
     */
    #[Locked]
    public ?int $deletingId = null;

    /**
     * Whether the delete confirmation is open.
     *
     * @since 1.0.0
     *
     * @var bool
     */
    public bool $confirmingDelete = false;

    /**
     * Authorizes the screen.
     *
     * @since 1.0.0
     *
     * @return void
     */
    public function mount(): void
    {
        $this->authorizeTable();
    }

    /**
     * Opens the drawer for a new subscription.
     *
     * @since 1.0.0
     *
     * @return void
     */
    public function create(): void
    {
        $this->authorizeEcommerce( 'create', WebhookSubscription::class );

        $this->resetErrorBag();
        $this->subscriptionId = null;
        $this->form           = [ 'name' => '', 'url' => '', 'events' => [], 'is_active' => true ];
        $this->editing        = true;
    }

    /**
     * Opens the drawer for an existing subscription.
     *
     * @since 1.0.0
     *
     * @param  int  $id  Subscription id.
     *
     * @return void
     */
    public function edit( int $id ): void
    {
        $subscription = WebhookSubscription::query()->find( $id );

        $this->authorizeEcommerceAbility( 'webhookSubscription.update', $subscription );

        if ( null === $subscription ) {
            return;
        }

        $this->resetErrorBag();
        $this->subscriptionId = (int) $subscription->id;
        $this->form           = [
            'name'      => (string) $subscription->name,
            'url'       => (string) $subscription->url,
            'events'    => array_values( array_map( 'strval', (array) $subscription->events ) ),
            'is_active' => (bool) $subscription->is_active,
        ];
        $this->editing        = true;
    }

    /**
     * Saves the drawer. A new subscription's secret is shown once.
     *
     * @since 1.0.0
     *
     * @return void
     */
    public function save(): void
    {
        $subscription = null === $this->subscriptionId ? null : WebhookSubscription::query()->find( $this->subscriptionId );

        if ( null === $subscription ) {
            $this->authorizeEcommerce( 'create', WebhookSubscription::class );

            if ( null !== $this->subscriptionId ) {
                // Deleted elsewhere while the drawer was open: don't recreate it.
                $this->editing        = false;
                $this->subscriptionId = null;
                $this->toastWarning( __( 'This subscription was deleted.' ), __( 'Someone deleted it while you were editing, so your changes were not saved.' ) );

                return;
            }
        } else {
            $this->authorizeEcommerceAbility( 'webhookSubscription.update', $subscription );
        }

        $base = WebhookSubscriptionRequest::baseRules();

        $this->validate(
            [
                'form.name'      => [ 'required', ...$base['name'] ],
                'form.url'       => [ 'required', ...$base['url'] ],
                'form.events'    => [ 'required', ...$base['events'] ],
                'form.events.*'  => [ 'distinct', ...$base['events.*'] ],
                'form.is_active' => [ 'boolean' ],
            ],
            [],
            [
                'form.name'      => __( 'name' ),
                'form.url'       => __( 'URL' ),
                'form.events'    => __( 'events' ),
                'form.events.*'  => __( 'event' ),
                'form.is_active' => __( 'active' ),
            ],
        );

        $data = [
            'name'      => trim( (string) $this->form['name'] ),
            'url'       => trim( (string) $this->form['url'] ),
            'events'    => array_values( array_map( 'strval', (array) $this->form['events'] ) ),
            'is_active' => (bool) $this->form['is_active'],
        ];

        $service = app( WebhookSubscriptionService::class );

        if ( null !== $subscription ) {
            $service->update( $subscription, $data );

            $this->editing = false;
            $this->toastSuccess( __( 'Subscription ":name" saved.', [ 'name' => $subscription->name ] ) );

            return;
        }

        $created = $service->create( $data );

        if ( null === $created ) {
            $this->toastError( __( 'The subscription was not created.' ), __( 'A store extension refused it.' ) );

            return;
        }

        $this->editing = false;
        $this->revealSecret( (string) $created->secret );
        $this->toastSuccess( __( 'Subscription ":name" created.', [ 'name' => $created->name ] ) );
    }

    /**
     * Asks to confirm deleting a subscription.
     *
     * @since 1.0.0
     *
     * @param  int  $id  Subscription id.
     *
     * @return void
     */
    public function confirmDelete( int $id ): void
    {
        $subscription = WebhookSubscription::query()->find( $id );

        $this->authorizeEcommerceAbility( 'webhookSubscription.delete', $subscription );

        $this->deletingId       = $subscription?->id;
        $this->confirmingDelete = null !== $subscription;
    }

    /**
     * Dismisses the delete confirmation.
     *
     * @since 1.0.0
     *
     * @return void
     */
    public function cancelDelete(): void
    {
        $this->deletingId       = null;
        $this->confirmingDelete = false;
    }

    /**
     * Deletes the subscription waiting for confirmation, once per token.
     *
     * @since 1.0.0
     *
     * @param  string  $token  The action token minted with the confirmation.
     *
     * @return void
     */
    public function delete( string $token ): void
    {
        $subscription = null === $this->deletingId || ! $this->confirmingDelete ? null : WebhookSubscription::query()->find( $this->deletingId );

        $this->authorizeEcommerceAbility( 'webhookSubscription.delete', $subscription );

        if ( null === $subscription ) {
            $this->cancelDelete();

            return;
        }

        $name = (string) $subscription->name;

        $deleted = $this->withActionToken( $token, 'delete', static function () use ( $subscription ): bool {
            $subscription->delete();

            return true;
        }, $subscription );

        $this->cancelDelete();

        if ( true === $deleted ) {
            if ( $this->subscriptionId === (int) $subscription->id ) {
                $this->editing        = false;
                $this->subscriptionId = null;
            }

            $this->toastSuccess( __( 'Subscription ":name" deleted.', [ 'name' => $name ] ) );
        }
    }

    /**
     * @since 1.0.0
     *
     * @return View
     */
    public function render(): View
    {
        $user     = auth()->user();
        $rotating = null === $this->rotatingId || ! $this->confirmingRotate ? null : WebhookSubscription::query()->find( $this->rotatingId );
        $deleting = null === $this->deletingId || ! $this->confirmingDelete ? null : WebhookSubscription::query()->find( $this->deletingId );

        return view( 'ecommerce-admin::livewire.webhooks.index', $this->resourceTableData() + [
            'canCreate'    => $this->canEcommerce( 'create', WebhookSubscription::class ),
            'canUpdate'    => Authorization::allows( $user, 'webhookSubscription.update' ),
            'canDelete'    => Authorization::allows( $user, 'webhookSubscription.delete' ),
            'eventOptions' => Webhooks::eventOptions( (array) $this->form['events'] ),
            'rotating'     => $rotating,
            'rotateToken'  => null === $rotating ? null : $this->actionToken( 'rotate', $rotating ),
            'deleting'     => $deleting,
            'deleteToken'  => null === $deleting ? null : $this->actionToken( 'delete', $deleting ),
        ] );
    }

    /**
     * @since 1.0.0
     *
     * @return void
     */
    protected function authorizeTable(): void
    {
        $this->authorizeEcommerce( 'viewAny', WebhookSubscription::class );
    }

    /**
     * @since 1.0.0
     *
     * @return string
     */
    protected function tableScreen(): string
    {
        return 'webhooks';
    }

    /**
     * @since 1.0.0
     *
     * @return ResourceQuery
     */
    protected function tableQuery(): ResourceQuery
    {
        return new WebhookSubscriptionsQuery();
    }

    /**
     * @since 1.0.0
     *
     * @return string
     */
    protected function tableCaption(): string
    {
        return __( 'Webhook subscriptions' );
    }

    /**
     * @since 1.0.0
     *
     * @return array<int, array<string, mixed>>
     */
    protected function tableColumns(): array
    {
        $cells = 'ecommerce-admin::livewire.webhooks.cells.';

        return [
            [
                'key'      => 'name',
                'label'    => __( 'Name' ),
                'sortable' => true,
                'view'     => $cells . 'name',
                'export'   => static fn ( WebhookSubscription $subscription ): string => (string) $subscription->name,
            ],
            [
                'key'    => 'url',
                'label'  => __( 'URL' ),
                'view'   => $cells . 'url',
                'export' => static fn ( WebhookSubscription $subscription ): string => (string) $subscription->url,
            ],
            [
                'key'    => 'events',
                'label'  => __( 'Events' ),
                'view'   => $cells . 'events',
                'export' => static fn ( WebhookSubscription $subscription ): string => implode( ', ', (array) $subscription->events ),
            ],
            [
                'key'    => 'state',
                'label'  => __( 'State' ),
                'view'   => $cells . 'state',
                'export' => static fn ( WebhookSubscription $subscription ): string => $subscription->is_active ? __( 'Active' ) : __( 'Disabled' ),
            ],
            [
                'key'      => 'last_success',
                'label'    => __( 'Last success' ),
                'sortable' => true,
                'view'     => $cells . 'date',
                'export'   => static fn ( WebhookSubscription $subscription ): string => Webhooks::dateTime( $subscription->last_success_at ),
            ],
            [
                'key'      => 'last_failure',
                'label'    => __( 'Last failure' ),
                'sortable' => true,
                'view'     => $cells . 'date',
                'export'   => static fn ( WebhookSubscription $subscription ): string => Webhooks::dateTime( $subscription->last_failure_at ),
            ],
            [
                'key'      => 'failures',
                'label'    => __( 'Consecutive failures' ),
                'sortable' => true,
                'class'    => 'text-end',
                'value'    => static fn ( WebhookSubscription $subscription ): string => (string) (int) $subscription->consecutive_failures,
                'export'   => static fn ( WebhookSubscription $subscription ): int => (int) $subscription->consecutive_failures,
            ],
            [
                'key'        => 'actions',
                'label'      => __( 'Actions' ),
                'class'      => 'text-end',
                'view'       => $cells . 'actions',
                'exportable' => false,
            ],
        ];
    }

    /**
     * @since 1.0.0
     *
     * @return array<int, array<string, mixed>>
     */
    protected function tableFilters(): array
    {
        return [
            [
                'key'     => 'active',
                'label'   => __( 'State' ),
                'type'    => 'select',
                'options' => [
                    [ 'id' => '1', 'name' => __( 'Active' ) ],
                    [ 'id' => '0', 'name' => __( 'Disabled' ) ],
                ],
            ],
        ];
    }

    /**
     * @since 1.0.0
     *
     * @return array<int, array<string, mixed>>
     */
    protected function tableBulkActions(): array
    {
        return [ $this->exportBulkAction() ];
    }
}
